baseURL = "https://blizinski.pl/"
languageCode = "pl-pl"
title = "Harmonia jazzowa na gitarze"
defaultContentLanguage = "pl"
theme = "porting"
enableGitInfo = true
[taxonomies]
  kategoria = "kategorie"
[params]
  description = "Chwyty akordowe, dlaczego akurat takie, oraz jak je łączyć ze sobą."
  organization = "Maciej Bliziński"
  logo = "/images/android-chrome-192x192.png"
[params.author]
  name = "Maciej Bliziński"
  url = "https://instagram.com/automaciej"
  image = ""
[params.maintainer]
  name = "Maciej Bliziński"
  url = "https://www.facebook.com/maciej.blizinski"
  image = "/images/automaciej-400px.jpg"
  twitter = "automaciej_pl"
  github = "automaciej"
