baseURL = "https://blizinski.pl/"
languageCode = "pl-pl"
title = "Gitara Jazzowa"
defaultContentLanguage = "pl"
theme = "porting"
[taxonomies]
kategoria = "kategorie"
[params]
description = """książka polskiego gitarzysty jazzowego, Marka Blizińskiego"""
